### ISSUE TITLE
feat: add ERC721 burn

### ISSUE THREAD

**Issue by NFTicks** [alephao/solidity-benchmarks#5]
Mostly implemented on my fork based on transferFrom logic. N/A for ERC721B.

**Comment by NFTicks** [comment]
Updated support for .gyb, impl tested and available on my fork's dev branch
https://github.com/NFTicks/solidity-benchmarks/blob/dev/ERC721.md

**Comment by alephao** [comment]
Hey @NFTicks, looking good, will you open a PR to add it?

**Comment by alephao** [comment]
Done on #7
